### ISSUE TITLE
Where is development happening?

### ISSUE THREAD

**Issue by Eh2406** [UDST/choicemodels#1]
Hi, how can we get involved. We need to build a household choice model soon and are happy to help. Where is development happening? Where is it being discussed?

cc: @smmaurer @semcogli

**Comment by waddell** [comment]
Hi, glad to know you're ready to help.  Most of the discussion is happening in person with @smmaurer and @timothyb0912 and Feras at Berkeley, and we're in the process of planning the addition of sampling methods to support location choice models now -- trying to get that done in the next month or so.  Hoping to have an example for using this from orca/urbansim not long after that.  We'll try to make more of the issues/roadmap visible as github issues, to make it more transparent going forward.  But it is still in a formative stage right now.

**Comment by waddell** [comment]
What kind of choice model are you planning to build?

**Comment by Eh2406** [comment]
I believe we are building a household choose model, but I am new so @semcogli can give you more details.

In person is fast. I get how in the formative stage speed is important. When you have time to slow down, we are hear to work together on it.

**Comment by waddell** [comment]
Sounds good. I'll close this for now and we'll be forking the UAL branch to UDST as soon as we can, at which point issues will be easier to engage with.

**Comment by semcogli** [comment]
@Eh2406 Paul and others,

As Jacob said, we are looking forward to building HH location choice model for the new forecast. And we would like to test out this new model. From the user conference presentation, it looks like pylogit can handle estimation if the choice sample is random but is still not ready for more complicated situation, such as sampling housing units from buildings, which may have one or more units. I assume the sampling method you are working on will include this? Anyway, it will be our pleasure to test this new model and integrate it in our forecast work. 

@Eh2406 @smmaurer

**Comment by smmaurer** [comment]
Hi, I wanted to add some information here.

The core estimation libraries that are going into ChoiceModels are in good shape, and for now you can find them at [timothyb0912/pylogit](https://github.com/timothyb0912/pylogit) and [ual/lccm](https://github.com/ual/lccm).

ChoiceModels will add optimizations for large choice sets and sampling of alternatives, and have an API that's more similar to Statsmodels. That work is happening in the [ual/choicemodels](https://github.com/ual/choicemodels) fork, but it's still early in development.

@eh2406 @semcogli In the meantime, the UrbanSim library already has a module that works well for household location choice with random sampling of alternatives. It's the [MNLDiscreteChoiceModel](https://github.com/UDST/urbansim/blob/master/urbansim/models/dcm.py) class in urbansim.models, and there are usage examples in MTC's Bay Area UrbanSim repo and other places.

Hope this helps!

**Comment by bridwell** [comment]
I'm not sure if this helps, or how to best collaborate, but we've done a fair amount of work on the prediction/simulation side, specifically in regard to sampling of alternatives when the alternatives have capacities (I don't believe this is supported in the Urbansim DCM at this time). The typical use case is for household location choice model with household variables such as income as well building variables such as price.

This is still going through some refactoring and updates, but see:
https://github.com/AZMAG/smartpy_core/blob/master/smartpy_core/choice.py#L491
https://github.com/AZMAG/smartpy_core/blob/master/smartpy_core/tests/test_choice.py#L146
