### ISSUE TITLE
TypeError when fitting a MultinomialLogit model

### ISSUE THREAD

**Issue by smmaurer** [UDST/choicemodels#12]
Arezoo (@arezoo-bz) is getting an unusual error trying to fit `MultinomialLogit` models. The same notebook runs on other machines without a problem. We'll update this issue when we find a solution or work-around.

<img width="790" alt="screen shot 2017-07-26 at 10 56 09" src="https://user-images.githubusercontent.com/3768016/28736043-eedd0756-739c-11e7-961b-e635e70d83d4.png">
<img width="769" alt="screen shot 2017-07-26 at 10 56 19" src="https://user-images.githubusercontent.com/3768016/28736048-f12ef83e-739c-11e7-91ca-afd24ddbf7f5.png">

**Comment by gboeing** [comment]
Is there a NaN somewhere that's being cast to int?

**Comment by Arezoo-bz** [comment]
@gboeing No NAN in the dataset. 
@smmaurer I updated anaconda and all other requirements... But still, I get the same error. I also deleted the %%time from my codes, but it didn't change anything. Weird problem!

**Comment by waddell** [comment]
I just replicated the error on my iMac.  Conda is up to date, and I did a fresh install of pylogit, choicemodels, updated urbansim. Numpy 1.12.1

**Comment by waddell** [comment]
pandas is 0.20.1, and Python is 3.5.3.  Followed the install instructions in choicemodels.

**Comment by smmaurer** [comment]
Interesting. How much of the [destination choice notebook](https://github.com/UDST/choicemodels/blob/master/notebooks/Destination-choice-models-01.ipynb) will run before triggering this error? Here's a [shortcut](https://www.dropbox.com/sh/x59zemt3o1rfopi/AADmxRMYZr7CSOCdA8QlWI73a?dl=0) to download the data files. 

I'll try to replicate the error in a virtual environment so i can troubleshoot things.

**Comment by waddell** [comment]
It runs all the way to the estimation cell without error.

**Comment by waddell** [comment]
And it fails even if I drop all but one variable, regardless of which one remains.

**Comment by smmaurer** [comment]
Ok, I tracked down the cause and this should be fixed in the latest PR (#13). Full explanation below for the curious!

@Arezoo-bz, when you have a chance, do a `git pull` on choicemodels, restart the Jupyter kernel, and try running the code again. Let me know if it works.

-----

The culprit was this division operator:  https://github.com/UDST/choicemodels/pull/13/files

In Python 3, division returns a float even if both operands are integers (see [PEP 238](https://docs.python.org/release/2.2.3/whatsnew/node7.html)).

Numpy used to silently accept floats as indexes if they were "close" in value to ints, but as of v1.12 it now raises a TypeError ([release notes](http://numpy.readthedocs.io/en/latest/release.html)).

So the combination of these things caused a crash on machines running Python 3 and Numpy > 1.12, but now it's fixed by using the correct integer division operator.

**Comment by waddell** [comment]
Confirmed, this fixed the problem.  Nice detective work!
