### ISSUE TITLE
Remove UrbanSim dependency

### ISSUE THREAD

**Issue by gboeing** [UDST/choicemodels#14]
What's the level of effort to remove the UrbanSim dependency? It looks like it's just used for logging right? Yet it creates a substantially more involved install process ([see also](https://github.com/UDST/choicemodels/pull/13#issuecomment-319243920)). I could look into refactoring later this week potentially.

**Comment by gboeing** [comment]
@smmaurer

**Comment by smmaurer** [comment]
Good idea. Yeah, it looks easy to remove -- the only usage I see is for a logging helper function.

https://github.com/UDST/choicemodels/blob/master/choicemodels/mnl.py#L653

There could be something in the unit tests too; I haven't checked.

**Comment by gboeing** [comment]
Sounds good. Will check it out soon.
