### ISSUE TITLE
official release

### ISSUE THREAD

**Issue by gboeing** [UDST/choicemodels#18]
Moving this from slack channel conversation to a GitHub issue for tracking. We should release a v0.1 of choicemodels. @smmaurer do you want to verify the current codebase status or make any additional commits to include 0.1? After that, I can package and release on pypi and conda. 

Also relevant, we should wait for this pylogit issue to be closed (ie, new release) before we release choicemodels: https://github.com/timothyb0912/pylogit/issues/15

**Comment by smmaurer** [comment]
I just did some docstring cleanup and set up a placeholder for sphinx documentation. I'll put that together and clean up the README, and then we should be ready for 0.1.

It seems common for projects to host sphinx docs in Github Pages, but perhaps easier and cleaner to host them on readthedocs.io. That way we would only be tracking the source files in git, not the build files. So fewer merge conflicts, cleaner repo, and easier build process. Do you have an opinion here?

Placeholder - http://choicemodels.readthedocs.io/

**Comment by gboeing** [comment]
I would endorse the readthedocs plan.

**Comment by waddell** [comment]
I second that motion.

**Comment by gboeing** [comment]
I can help tackle code packaging and readthedocs setup when this is ready.

**Comment by gboeing** [comment]
The latest pylogit has been released, so we should be all ready to proceed.

**Comment by gboeing** [comment]
@smmaurer if you can confirm docstrings etc are in a reasonable state, I will start the packaging work for release. Would be important to get a 0.1 release out there in light of our related deliverables over the coming month.

**Comment by smmaurer** [comment]
Everything looks good to me. Go for it!
