### ISSUE TITLE
Known probability distributions in sampling.py

### ISSUE THREAD

**Issue by Eh2406** [UDST/choicemodels#2]
@apdjustino has a PR for ["Known probability distributions in sampling.py"](https://github.com/UDST/urbansim/pull/149) We should make sure that their use case is accounted for in the new code.

**Comment by waddell** [comment]
Will have to look at that more closely, but sampling.py in utils is related to the transition model so will need to have someone look at the backlog of issues including the one you refer to.  Sampling of alternatives in ChoiceModels will be quite different and tied to the econometrics of the estimator for different types of choice models (MNL, NL, Mixed Logit, Latent Class, etc).  I'm closing this issue for now in relation to choice models.
