### ISSUE TITLE
Documenting the development workflow

### ISSUE THREAD

**Issue by smmaurer** [UDST/choicemodels#35]
Hey @gboeing, could you write up a brief description of the process for updating the documentation and putting together new pip/conda-forge releases, when you have a chance? We could make a wiki page or a section in the README for this..

**Comment by gboeing** [comment]
@smmaurer regarding release, see here: https://gist.github.com/gboeing/dcfaf5e13fad16fc500717a3a324ec17

I'll write up a short intro to readthedocs in this repo

**Comment by smmaurer** [comment]
That's fabulous, thanks! Gist is fine for the other part too, if that makes it easier to reuse elsewhere.
